#  ,gggggggggggg,                                                               
# dP"""88""""""Y8b,                                                             
# Yb,  88       `8b,                                                            
#  `"  88        `8b                                                            
#      88         Y8                                                            
#      88         d8 gg      gg   ,ggg,,ggg,    ,ggg,                           
#      88        ,8P I8      8I  ,8" "8P" "8,  i8" "8i                          
#      88       ,8P' I8,    ,8I  I8   8I   8I  I8, ,8I                          
#      88______,dP' ,d8b,  ,d8b,,dP   8I   Yb, `YbadP'                          
#     888888888P"   8P'"Y88P"`Y88P'   8I   `Y8888P"Y888                         
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#  ,ggg, ,ggg,_,ggg,                                                            
# dP""Y8dP""Y88P""Y8b                                                 ,dPYb,    
# Yb, `88'  `88'  `88                                                 IP'`Yb    
#  `"  88    88    88                                gg               I8  8I    
#      88    88    88                                ""               I8  8'    
#      88    88    88   ,ggg,     ,g,       ,g,      gg     ,gggg,gg  I8 dPgg,  
#      88    88    88  i8" "8i   ,8'8,     ,8'8,     88    dP"  "Y8I  I8dP" "8I 
#      88    88    88  I8, ,8I  ,8'  Yb   ,8'  Yb    88   i8'    ,8I  I8P    I8 
#      88    88    Y8, `YbadP' ,8'_   8) ,8'_   8) _,88,_,d8,   ,d8b,,d8     I8,
#      88    88    `Y8888P"Y888P' "YY8P8PP' "YY8P8P8P""Y8P"Y8888P"`Y888P     `Y8
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               

  # Accent and UI colors
  accent = "#8c4f2a"
  active_border_color = "#a45e33"
  active_tab_background = "#8c4f2a"

  # Cursor colors
  cursor = "#47362b"

  # Primary colors
  foreground = "#47362b"
  background = "#dcd8d6"

  # Selection colors
  selection_foreground = "#f3ece7"
  selection_background = "#8c4f2a"

  # Normal colors (ANSI 0-7)
  color0 = "#dcd8d6" # base
  color1 = "#7a3827" # danger / deleted / error
  color2 = "#6f5a36" # success / created / strings
  color3 = "#8a5d24" # warning / constants
  color4 = "#8c4f2a" # accent / modified / keywords
  color5 = "#6e4633" # secondary accent / visited / UI alt
  color6 = "#355f68" # info / links / types
  color7 = "#47362b" # primary text

  # Bright colors (ANSI 8-15)
  color8 = "#6e6259"  # muted / comments / borders
  color9 = "#5f261c"  # bright danger
  color10 = "#5f4c2a" # bright success
  color11 = "#704713" # bright warning
  color12 = "#a45e33" # bright accent / active border
  color13 = "#8b5a40" # bright secondary accent
  color14 = "#244c56" # bright info
  color15 = "#2f2118" # deepest text / high emphasis

#    __                    
#   /\_\/|\  _|            
#  |    ||/ / |            
#   \__/ |_/\/|_/          
#   /|  _  |)   _  |)   _  
#  | | / \_|/\_/ \_|/\_/ \_
#   \|/\_/  \/ \_/  \/ \_/ 
#   (|                     