#  ,gggggggggggg,                                                               
# dP"""88""""""Y8b,                                                             
# Yb,  88       `8b,                                                            
#  `"  88        `8b                                                            
#      88         Y8                                                            
#      88         d8 gg      gg   ,ggg,,ggg,    ,ggg,                           
#      88        ,8P I8      8I  ,8" "8P" "8,  i8" "8i                          
#      88       ,8P' I8,    ,8I  I8   8I   8I  I8, ,8I                          
#      88______,dP' ,d8b,  ,d8b,,dP   8I   Yb, `YbadP'                          
#     888888888P"   8P'"Y88P"`Y88P'   8I   `Y8888P"Y888                         
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#  ,ggg, ,ggg,_,ggg,                                                            
# dP""Y8dP""Y88P""Y8b                                                 ,dPYb,    
# Yb, `88'  `88'  `88                                                 IP'`Yb    
#  `"  88    88    88                                gg               I8  8I    
#      88    88    88                                ""               I8  8'    
#      88    88    88   ,ggg,     ,g,       ,g,      gg     ,gggg,gg  I8 dPgg,  
#      88    88    88  i8" "8i   ,8'8,     ,8'8,     88    dP"  "Y8I  I8dP" "8I 
#      88    88    88  I8, ,8I  ,8'  Yb   ,8'  Yb    88   i8'    ,8I  I8P    I8 
#      88    88    Y8, `YbadP' ,8'_   8) ,8'_   8) _,88,_,d8,   ,d8b,,d8     I8,
#      88    88    `Y8888P"Y888P' "YY8P8PP' "YY8P8P8P""Y8P"Y8888P"`Y888P     `Y8
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               
#                                                                               

[colors-dark]
alpha=0.75
foreground=47362b
background=dcd8d6
cursor=dcd8d6 47362b
selection-foreground=f3ece7
selection-background=8c4f2a

regular0=dcd8d6
regular1=7a3827
regular2=6f5a36
regular3=8a5d24
regular4=8c4f2a
regular5=6e4633
regular6=355f68
regular7=47362b

bright0=6e6259
bright1=5f261c
bright2=5f4c2a
bright3=704713
bright4=a45e33
bright5=8b5a40
bright6=244c56
bright7=2f2118

#    __                    
#   /\_\/|\  _|            
#  |    ||/ / |            
#   \__/ |_/\/|_/          
#   /|  _  |)   _  |)   _  
#  | | / \_|/\_/ \_|/\_/ \_
#   \|/\_/  \/ \_/  \/ \_/ 
#   (|                     