# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 


# Background and foreground colors
background = #dcd8d6
foreground = #47362b

# Standard colors
palette = 0=#dcd8d6
palette = 1=#7a3827
palette = 2=#6f5a36
palette = 3=#8a5d24
palette = 4=#8c4f2a
palette = 5=#6e4633
palette = 6=#355f68
palette = 7=#47362b

# Bright colors
palette = 8=#6e6259
palette = 9=#5f261c
palette = 10=#5f4c2a
palette = 11=#704713
palette = 12=#a45e33
palette = 13=#8b5a40
palette = 14=#244c56
palette = 15=#2f2118

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
