-- Generated by scripts/hypr2lua.
-- Source: omarchy-dune-messiah-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(a45e33ff)", "rgba(8c4f2aff)", "rgba(6e4633ff)" },
}
local inactiveBorderColor = "rgb(6e6259)"
local groupActiveColor = "rgb(8c4f2a)"
local groupLockedColor = "rgb(355f68)"
local shadowColor = "rgba(2f2118b8)"
local inactiveShadowColor = "rgba(2f211872)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 3,
    gaps_in = 6,
    gaps_out = 12,
  },
  group = {
    col = {
      border_active = groupActiveColor,
      border_inactive = inactiveBorderColor,
      border_locked_active = groupLockedColor,
      border_locked_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    active_opacity = 0.990,
    inactive_opacity = 0.975,
    dim_inactive = true,
    dim_strength = 0.08,
    blur = {
      enabled = true,
      size = 3,
      passes = 2,
      noise = 0.05,
      vibrancy = 0.24,
      vibrancy_darkness = 0.78,
      brightness = 0.62,
      contrast = 0.44,
      special = false,
    },
    shadow = {
      enabled = true,
      color = shadowColor,
      range = 18,
      render_power = 3,
      color_inactive = inactiveShadowColor,
    },
  },
})

hl.curve("sandwalk", { type = "bezier", points = { { 0.35, 0 }, { 0.65, 1 } } })

hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 22,
  bezier = "sandwalk",
  style = "once",
})
