# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #dcd8d6
foreground            #47362b

# black
color0  #dcd8d6
color8  #6e6259

# red
color1  #7a3827
color9  #5f261c

# green
color2  #6f5a36
color10 #5f4c2a

# yellow
color3  #8a5d24
color11 #704713

# blue
color4  #8c4f2a
color12 #a45e33

# magenta
color5  #6e4633
color13 #8b5a40

#cyan
color6  #355f68
color14 #244c56

#white
color7  #47362b
color15 #2f2118

#   ______   __       ______                                       
#  /_____/\ /_/\     /_____/\                                      
#  \:::_ \ \\:\ \    \:::_ \ \                                     
#   \:\ \ \ \\:\ \    \:\ \ \ \                                    
#    \:\ \ \ \\:\ \____\:\ \ \ \                                   
#     \:\_\ \ \\:\/___/\\:\/.:| |                                  
#   ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
#  /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
#  \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#    /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#    \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#     \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#      \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#  
